name: pansy-dev

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=1
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5555:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=a@a.com
      - PGADMIN_DEFAULT_PASSWORD=0
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  redisinsight:
    image: redislabs/redisinsight
    ports:
      - '8001:8001'
    volumes:
      - redisinsight-data:/db

  elasticsearch:
    image: elasticsearch:7.17.9
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.17.9
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

volumes:
  postgres-data:
  pgadmin-data:
  redis-data:
  redisinsight-data:
  elasticsearch-data: